name: Angular FTP Staging Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the Node.js version as needed
      - run: yarn -v # Optional: Check Yarn version
      
      - name: Install Dependencies with Yarn
        run: yarn install --legacy-peer-deps
        
      - name: Build Node App with Yarn
        run: yarn build
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: '/'
          local-dir: './build/' # Change this to your build output directory
